include: analysis_lint_rules.yaml
#include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - "*.g.dart"
    - "*.freezed.dart"
    - "*.gr.dart"
    - "*.config.dart"
    - "*.gen.dart"
