include: analysis_lint_rules.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"
    - "**/*.al.dart"
    - "**/*.mocks.dart"
